allure.results.directory=target/allure-results
allure.link.issue.pattern=https://github.com/wbandara-tech/selenium-testng-ecommerce-framework/issues/{}
allure.link.tms.pattern=https://github.com/wbandara-tech/selenium-testng-ecommerce-framework/issues/{}

